#ifndef HANDLE_H
#define HANDLE_H
#pragma once
#include <windows.h>
#include "structs.h"

HWND MAIN_WINDOW;
HWND DMM_WINDOW;
HWND BUTTON_TOP[10];
HWND BUTTON_LEFT[4];
HWND BUTTON_RIGHT[4];
HWND BUTTON_BOTTOM[10];

HWND MSGBOX;
std::vector<HWND> BUTTON_KEYBOARD_NUMBERS(10, NULL);
std::vector<HWND> BUTTON_KEYBOARD_ALPHABET(26, NULL);
HWND BUTTON_KEYBOARD_PERIOD;
HWND BUTTON_KEYBOARD_ENTER;
HWND BUTTON_KEYBOARD_SPACE;
HWND BUTTON_KEYBOARD_BACKSPACE;

DISPLAY_CONFIG sDisplay_config;

#endif