@set allusersprofile=c:\programdata
@set appdata=c:\users\gemini\appdata\roaming
@set commandprompttype=native
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set complus_installroot=
@set complus_version=
@set computername=idps-03
@set comspec=c:\windows\system32\cmd.exe
@set cuda_path=c:\program files\nvidia gpu computing toolkit\cuda\v11.5
@set cuda_path_v11_5=c:\program files\nvidia gpu computing toolkit\cuda\v11.5
@set devenvdir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set dotnet_msbuild_sdk_resolver_sdks_dir=c:\program files (x86)\pvs-studio\buildtools\sdks
@set driverdata=c:\windows\system32\drivers\driverdata
@set extensionsdkdir=c:\program files (x86)\microsoft sdks\windows kits\10\extensionsdks
@set fps_browser_app_profile_string=internet explorer
@set fps_browser_user_profile_string=default
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework64\
@set frameworkdir64=c:\windows\microsoft.net\framework64\
@set frameworkversion=v4.0.30319
@set frameworkversion64=v4.0.30319
@set fsharpinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\tools
@set homedrive=c:
@set homepath=\users\gemini
@set include=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\atlmfc\include;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\include;c:\program files (x86)\windows kits\netfxsdk\4.8\include\um;c:\program files (x86)\windows kits\10\include\10.0.22000.0\ucrt;c:\program files (x86)\windows kits\10\include\10.0.22000.0\shared;c:\program files (x86)\windows kits\10\include\10.0.22000.0\um;c:\program files (x86)\windows kits\10\include\10.0.22000.0\winrt;c:\program files (x86)\windows kits\10\include\10.0.22000.0\cppwinrt
@set lib=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\lib\x64;c:\program files (x86)\windows kits\netfxsdk\4.8\lib\um\x64;c:\program files (x86)\windows kits\10\lib\10.0.22000.0\ucrt\x64;c:\program files (x86)\windows kits\10\lib\10.0.22000.0\um\x64
@set libpath=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\atlmfc\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\lib\x64;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\lib\x86\store\references;c:\program files (x86)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files (x86)\windows kits\10\references\10.0.22000.0;c:\windows\microsoft.net\framework64\v4.0.30319
@set localappdata=c:\users\gemini\appdata\local
@set logonserver=\\idps-03
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools\msbuild.exe
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.8\
@set number_of_processors=8
@set nvcudasamples11_5_root=c:\programdata\nvidia corporation\cuda samples\v11.5
@set nvcudasamples_root=c:\programdata\nvidia corporation\cuda samples\v11.5
@set nvtoolsext_path=c:\program files\nvidia corporation\nvtoolsext\
@set onedrive=c:\users\gemini\ronald\onedrive
@set onedriveconsumer=c:\users\gemini\ronald\onedrive
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\\extensions\microsoft\intellicode\cli;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\bin\hostx64\x64;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\vcpackages;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\teamfoundation\team explorer;c:\program files (x86)\microsoft visual studio\2019\community\msbuild\current\bin\roslyn;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools\x64;c:\program files (x86)\microsoft visual studio\2019\community\team tools\performance tools;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\\x64;c:\program files (x86)\microsoft visual studio\shared\common\vsperfcollectiontools\vs2019\;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\fsharp\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\devinit;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\windows kits\10\bin\x64;c:\program files (x86)\microsoft visual studio\2019\community\\msbuild\current\bin;c:\windows\microsoft.net\framework64\v4.0.30319;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\;c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\bin;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\libnvvp;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\microsoft vs code\bin;c:\program files\dotnet\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\lib\x64;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\include;c:\program files\nvidia corporation\nsight compute 2021.3.1\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\dotnet\;c:\users\gemini\appdata\local\microsoft\windowsapps;c:\users\gemini\appdata\local\githubdesktop\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\cmake\bin;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\ninja;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\linux\bin\connectionmanagerexe
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\gemini\appdata\local\microsoft\visualstudio\16.0_7e2fadf9\devenv.exe.config
@set platform=x64
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 140 stepping 1, genuineintel
@set processor_level=6
@set processor_revision=8c01
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\program files\windowspowershell\modules;c:\windows\system32\windowspowershell\v1.0\modules
@set public=c:\users\public
@set pvsbuildtools_extensionspath_current=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_extensionspath_vs2017=c:\windows\microsoft.net\framework64\
@set pvsbuildtools_extensionspath_vs2019=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_extensionspath_vs2022=c:\program files (x86)\microsoft visual studio\2019\community\msbuild
@set pvsbuildtools_installdir_current=c:\program files (x86)\microsoft visual studio\2019\community
@set pvsbuildtools_installdir_vs2019=c:\program files (x86)\microsoft visual studio\2019\community
@set pvsbuildtools_netcoresdkmajorversion=5
@set pvsbuildtools_vctargetspath_current=c:\program files (x86)\microsoft visual studio\2019\community\msbuild\microsoft\vc\v160\
@set pvsbuildtools_visualstudioversion_current=16.0
@set pvs_netcoresdkspath=c:\program files\dotnet\sdk\5.0.301\sdks
@set servicehublogsessionkey=ddf24026
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\gemini\appdata\local\temp
@set threadedwaitdialogdpicontext=-4
@set tmp=c:\users\gemini\appdata\local\temp
@set ucrtversion=10.0.22000.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=idps-03
@set userdomain_roamingprofile=idps-03
@set username=gemini
@set userprofile=c:\users\gemini
@set vbox_msi_install_path=c:\program files\oracle\virtualbox\
@set vcideinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\vc\
@set vcinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\
@set vctoolsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\
@set vctoolsredistdir=c:\program files (x86)\microsoft visual studio\2019\community\vc\redist\msvc\14.29.30036\
@set vctoolsversion=14.29.30037
@set visualstudiodir=c:\users\gemini\documents\visual studio 2019
@set visualstudioedition=microsoft visual studio community 2019
@set visualstudioversion=16.0
@set vs160comntools=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\
@set vsappiddir=c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\
@set vsappidname=devenv.exe
@set vscmd_arg_app_plat=desktop
@set vscmd_arg_host_arch=x64
@set vscmd_arg_tgt_arch=x64
@set vscmd_ver=16.10.3
@set vsinstalldir=c:\program files (x86)\microsoft visual studio\2019\community\
@set vslang=1033
@set vsskuedition=community
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\10\unionmetadata\10.0.22000.0;c:\program files (x86)\windows kits\10\references\10.0.22000.0
@set windowssdkbinpath=c:\program files (x86)\windows kits\10\bin\
@set windowssdkdir=c:\program files (x86)\windows kits\10\
@set windowssdklibversion=10.0.22000.0\
@set windowssdkverbinpath=c:\program files (x86)\windows kits\10\bin\10.0.22000.0\
@set windowssdkversion=10.0.22000.0\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\
@set zes_enable_sysman=1
@set __devinit_path=c:\program files (x86)\microsoft visual studio\2019\community\common7\tools\devinit\devinit.exe
@set __dotnet_add_64bit=1
@set __dotnet_preferred_bitness=64
@set __vscmd_preinit_path=c:\program files (x86)\microsoft visual studio\2019\community\vc\tools\msvc\14.29.30037\bin\hostx64\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x64;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools\x64;c:\program files (x86)\windows kits\10\bin\10.0.22000.0\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.8 tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\tools;c:\program files (x86)\microsoft visual studio\2019\community\common7\ide;c:\program files (x86)\html help workshop;c:\program files (x86)\pvs-studio\buildtools;c:\windows\microsoft.net\framework64\v4.0.30319\;c:\windows\microsoft.net\framework\v4.0.30319\;.\;c:\windows\microsoft.net\framework\v4.0.30319\;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\bin;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\libnvvp;c:\program files (x86)\common files\oracle\java\javapath;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\windows\system32\openssh\;c:\program files (x86)\nvidia corporation\physx\common;c:\program files\microsoft vs code\bin;c:\program files\dotnet\;c:\program files\microsoft sql server\130\tools\binn\;c:\program files\microsoft sql server\client sdk\odbc\170\tools\binn\;c:\program files\git\cmd;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\lib\x64;c:\program files\nvidia gpu computing toolkit\cuda\v11.5\include;c:\program files\nvidia corporation\nsight compute 2021.3.1\;c:\program files (x86)\windows kits\10\windows performance toolkit\;c:\program files (x86)\dotnet\;c:\users\gemini\appdata\local\microsoft\windowsapps;c:\users\gemini\appdata\local\githubdesktop\bin
@set __vscmd_script_err_count=0

@call "cl.exe" @"C:\temp\Pre.ARO-main\MMIConsoleApp\MMIConsoleApp\MMIConsoleApp.cpp.PVS-Studio.preprocess.cmd.rsp" 2>&1